server:
  port: 9000

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
      - id: VEHICLE-MANAGER
        uri: lb://VEHICLE-MANAGER
        predicates:
        - Path=/vehicle/**


