server:
  port: 0
spring:
  application:
    name: owner-manager
  datasource:
    url: jdbc:mysql://localhost:3306/vdmDbDev?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
